# Generated by Django 2.1.2 on 2018-10-06 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Peering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router', models.CharField(db_index=True, max_length=255)),
                ('netixlan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_peeringdb.NetworkIXLan')),
            ],
        ),
    ]
