# Generated by Django 2.2.12 on 2020-05-01 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name="ASRank",
            fields=[
                ("rank", models.PositiveIntegerField(verbose_name="CAIDA Rank")),
                (
                    "net",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="django_peeringdb.Network",
                        verbose_name="Network",
                    ),
                ),
            ],
        ),
    ]
